CREATE TABLE CATEGORIES (
    ID BIGINT PRIMARY KEY NOT NULL,
    CATEGORY VARCHAR NOT NULL
);

CREATE SEQUENCE CATEGORIES_SEQ
    INCREMENT BY 1
    START 1
    CACHE 1
    OWNED BY CATEGORIES.ID;

CREATE TABLE BOOKS (
    ID BIGINT PRIMARY KEY NOT NULL,
    TITLE VARCHAR NOT NULL,
    AUTHOR VARCHAR NOT NULL,
    IS_LOANED BOOLEAN DEFAULT FALSE,
    UNIQUE(TITLE, AUTHOR)
);

CREATE SEQUENCE BOOKS_SEQ
    INCREMENT BY 1
    START 1
    CACHE 1
    OWNED BY BOOKS.ID;

CREATE TABLE  BOOKS_CATEGORIES(
    BOOKS_ID  INTEGER REFERENCES BOOKS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CATEGORIES_ID integer REFERENCES CATEGORIES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (BOOKS_ID, CATEGORIES_ID)
);