spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/library?sslmode=disable
    username: sqladmin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db.changelog/dbchangelog.xml
  sql:
    init:
      platform: postgres
management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: always
      show-components: always
